version: "3"
services:
    web:
        image: abhsob/mom_poc_0817_dockerapp:1.0
        ports:
            - "6080:6080"
        depends_on:
            - redis
    redis:
        image: redis:3.2.4
